leftnav:
- identifier: external--1836900334-1701420104988
  name: Online Publication
  params:
    includeLicenseWarning: false
  url: https://bravenewplanet.org/
  weight: 10
- identifier: external-1262203527-1701420087437
  name: A Learner's Guide
  params:
    includeLicenseWarning: false
  url: https://www.ocw-openmatters.org/2020/11/02/brave-new-planet-a-learners-guide/
  weight: 20
